include $(CLEAR_VARS)

LOCAL_MODULE := micos

LOCAL_SRC_FILES :=
LOCAL_SRC_FILES += main.c
LOCAL_SRC_FILES += lib.c
LOCAL_SRC_FILES += vector.c
LOCAL_SRC_FILES += startup.s
LOCAL_LINKER_FILE := linker.ld

LOCAL_SRC_DIR := os

include $(BUILD_EXECUTABLE)
